Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - select_fdr
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.90000

Error on feature selection - select_fwe
Input X must be non-negative.

Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MinMaxScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.35000

Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MinMaxScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fpr
Input X must be non-negative.

Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MinMaxScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - select_fwe
Input X must be non-negative.

Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # Normalizer max # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fwe
Input X must be non-negative.

Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # Normalizer max # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fpr
Input X must be non-negative.

Error on calculation scores - fitting
Graph_based_Signatures # MinMaxScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # Normalizer max # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # MinMaxScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # MinMaxScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Toxicophores Fragments # Normalizer l1 # SelectFwe 0.10 chi2 # XGBClassifier 350 8 2 1.60

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 730, in inner_f
    return func(**kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/sklearn.py", line 1500, in fit
    train_dmatrix, evals = _wrap_evaluation_matrices(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/sklearn.py", line 521, in _wrap_evaluation_matrices
    train_dmatrix = create_dmatrix(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/sklearn.py", line 958, in _create_dmatrix
    return QuantileDMatrix(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 730, in inner_f
    return func(**kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 1529, in __init__
    self._init(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 1590, in _init
    _check_call(ret)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [15:45:05] /workspace/src/data/iterative_dmatrix.cc:202: Check failed: n_features >= 1 (0 vs. 1) : Data must has at least 1 column.
Stack trace:
  [bt] (0) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3effba) [0x7831f15effba]
  [bt] (1) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3f59b7) [0x7831f15f59b7]
  [bt] (2) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3f8858) [0x7831f15f8858]
  [bt] (3) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3a2a07) [0x7831f15a2a07]
  [bt] (4) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(XGQuantileDMatrixCreateFromCallback+0x2b0) [0x7831f1365c40]
  [bt] (5) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/lib-dynload/../../libffi.so.7(+0x69dd) [0x7832cad7a9dd]
  [bt] (6) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/lib-dynload/../../libffi.so.7(+0x6067) [0x7832cad7a067]
  [bt] (7) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x9319) [0x7832ca2eb319]
  [bt] (8) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x865a) [0x7832ca2ea65a]




Error on calculation scores - fitting
Toxicophores Fragments # Normalizer l1 # SelectFwe 0.10 chi2 # XGBClassifier 350 8 2 1.60

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 730, in inner_f
    return func(**kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/sklearn.py", line 1500, in fit
    train_dmatrix, evals = _wrap_evaluation_matrices(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/sklearn.py", line 521, in _wrap_evaluation_matrices
    train_dmatrix = create_dmatrix(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/sklearn.py", line 958, in _create_dmatrix
    return QuantileDMatrix(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 730, in inner_f
    return func(**kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 1529, in __init__
    self._init(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 1590, in _init
    _check_call(ret)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [15:45:05] /workspace/src/data/iterative_dmatrix.cc:202: Check failed: n_features >= 1 (0 vs. 1) : Data must has at least 1 column.
Stack trace:
  [bt] (0) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3effba) [0x7831f15effba]
  [bt] (1) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3f59b7) [0x7831f15f59b7]
  [bt] (2) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3f8858) [0x7831f15f8858]
  [bt] (3) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3a2a07) [0x7831f15a2a07]
  [bt] (4) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(XGQuantileDMatrixCreateFromCallback+0x2b0) [0x7831f1365c40]
  [bt] (5) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/lib-dynload/../../libffi.so.7(+0x69dd) [0x7832cad7a9dd]
  [bt] (6) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/lib-dynload/../../libffi.so.7(+0x6067) [0x7832cad7a067]
  [bt] (7) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x9319) [0x7832ca2eb319]
  [bt] (8) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x865a) [0x7832ca2ea65a]




Error on calculation scores - fitting
Toxicophores Fragments # Normalizer l1 # SelectFwe 0.10 chi2 # XGBClassifier 350 8 2 1.60

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 730, in inner_f
    return func(**kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/sklearn.py", line 1500, in fit
    train_dmatrix, evals = _wrap_evaluation_matrices(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/sklearn.py", line 521, in _wrap_evaluation_matrices
    train_dmatrix = create_dmatrix(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/sklearn.py", line 958, in _create_dmatrix
    return QuantileDMatrix(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 730, in inner_f
    return func(**kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 1529, in __init__
    self._init(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 1590, in _init
    _check_call(ret)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [15:45:05] /workspace/src/data/iterative_dmatrix.cc:202: Check failed: n_features >= 1 (0 vs. 1) : Data must has at least 1 column.
Stack trace:
  [bt] (0) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3effba) [0x7831f15effba]
  [bt] (1) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3f59b7) [0x7831f15f59b7]
  [bt] (2) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3f8858) [0x7831f15f8858]
  [bt] (3) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3a2a07) [0x7831f15a2a07]
  [bt] (4) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(XGQuantileDMatrixCreateFromCallback+0x2b0) [0x7831f1365c40]
  [bt] (5) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/lib-dynload/../../libffi.so.7(+0x69dd) [0x7832cad7a9dd]
  [bt] (6) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/lib-dynload/../../libffi.so.7(+0x6067) [0x7832cad7a067]
  [bt] (7) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x9319) [0x7832ca2eb319]
  [bt] (8) /home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x865a) [0x7832ca2ea65a]




Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - select_fwe
Input X must be non-negative.

Error on calculation scores - fitting
Fragments # Normalizer max # SelectFwe 0.35 chi2 # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Fragments # Normalizer max # SelectFwe 0.35 chi2 # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.15000

Error on calculation scores - fitting
Fragments # Normalizer max # SelectFwe 0.35 chi2 # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fpr
Input X must be non-negative.

Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures # Normalizer l2 # SelectFdr 0.40 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fwe
Input X must be non-negative.

Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures # Normalizer l2 # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MinMaxScaler # SelectFpr 0.30 chi2 # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures # Normalizer l2 # SelectFdr 0.40 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # RobustScaler True False # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures # Normalizer l2 # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MinMaxScaler # SelectFpr 0.30 chi2 # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures # Normalizer l2 # SelectFdr 0.40 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # RobustScaler True False # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures # Normalizer l2 # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MinMaxScaler # SelectFpr 0.30 chi2 # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # RobustScaler True False # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - select_fpr
Input X must be non-negative.

Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MinMaxScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # RobustScaler True False # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Toxicophores Fragments # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 50 750 logistic adam adaptive 1000 0.07

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MinMaxScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # RobustScaler True False # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # RobustScaler True False # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Toxicophores Fragments # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 50 750 logistic adam adaptive 1000 0.07

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MinMaxScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # Normalizer l1 # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MinMaxScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # RobustScaler True False # SelectFdr 0.40 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # RobustScaler True False # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # RobustScaler True False # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Toxicophores Fragments # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 50 750 logistic adam adaptive 1000 0.07

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures Toxicophores Fragments # RobustScaler True False # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MinMaxScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # Normalizer l1 # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # RobustScaler True False # SelectFdr 0.40 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # RobustScaler True False # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures Toxicophores Fragments # RobustScaler True False # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MinMaxScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # Normalizer l1 # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # RobustScaler True False # SelectFdr 0.40 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures Toxicophores Fragments # RobustScaler True False # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fpr
Input X must be non-negative.

Error on calculation scores - fitting
Graph_based_Signatures # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MaxAbsScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MaxAbsScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # Normalizer l1 # NoFeatureSelection # NeuroNets 50 750 logistic adam adaptive 1000 0.07

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MaxAbsScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # Normalizer l1 # NoFeatureSelection # NeuroNets 50 750 logistic adam adaptive 1000 0.07

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # Normalizer l1 # NoFeatureSelection # NeuroNets 50 750 logistic adam adaptive 1000 0.07

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - select_fpr
Input X must be non-negative.

Error on calculation scores - fitting
Toxicophores Fragments # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # RobustScaler True False # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Toxicophores Fragments # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MinMaxScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MinMaxScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # RobustScaler True False # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Toxicophores Fragments # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MinMaxScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures Toxicophores # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MinMaxScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # RobustScaler True False # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors # MinMaxScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures Toxicophores # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MinMaxScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures Toxicophores # MaxAbsScaler # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures Toxicophores # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # MinMaxScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores Fragments # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures Toxicophores # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fdr
Input X must be non-negative.

Error on calculation scores - fitting
Graph_based_Signatures # MinMaxScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Graph_based_Signatures Toxicophores # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores Fragments # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MinMaxScaler # SelectFpr 0.30 chi2 # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # MinMaxScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # MaxAbsScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores Fragments # MaxAbsScaler # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MinMaxScaler # SelectFpr 0.30 chi2 # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # MaxAbsScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Fragments # MinMaxScaler # SelectFpr 0.30 chi2 # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # MaxAbsScaler # SelectFdr 0.35 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fdr
Input X must be non-negative.

Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores Fragments # MaxAbsScaler # SelectFdr 0.40 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores Fragments # MaxAbsScaler # SelectFdr 0.40 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores Fragments # MaxAbsScaler # SelectFdr 0.40 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores Fragments # MaxAbsScaler # SelectFdr 0.40 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores Fragments # MaxAbsScaler # SelectFdr 0.40 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores Fragments # MaxAbsScaler # SelectFdr 0.40 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # RobustScaler True False # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # RobustScaler True False # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # Normalizer max # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # RobustScaler True False # NoFeatureSelection # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures # Normalizer max # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fdr
Input X must be non-negative.

Error on calculation scores - fitting
Graph_based_Signatures # Normalizer max # SelectPercentile 50 f_classif # NeuroNets 1000 5 3 relu sgd invscaling 3000 0.08

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - select_fwe
Input X must be non-negative.

Error on calculation scores - fitting
Fragments # MinMaxScaler # SelectFwe 0.05 chi2 # AdaBoostClassifier SAMME 50 0.20

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_weight_boosting.py", line 133, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on feature selection - select_fwe
Input X must be non-negative.

Error on calculation scores - fitting
Fragments # MinMaxScaler # SelectFwe 0.05 chi2 # AdaBoostClassifier SAMME 50 0.20

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_weight_boosting.py", line 133, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on feature selection - select_fwe
Input X must be non-negative.

Error on calculation scores - fitting
Fragments # MinMaxScaler # SelectFwe 0.05 chi2 # AdaBoostClassifier SAMME 50 0.20

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_weight_boosting.py", line 133, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - select_fwe
Input X must be non-negative.

