Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.70000

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.60000

Error on feature selection - select_fwe
Input X must be non-negative.

Error on calculation scores - fitting
Toxicophores # MinMaxScaler # SelectFdr 0.40 chi2 # ExtraTreesClassifier 75 gini 12 12 8 log2 None

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 363, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on feature selection - select_percentile
Input X must be non-negative.

Error on calculation scores - fitting
Fragments # MinMaxScaler # SelectFpr 0.50 f_classif # NeuroNets 25 1 tanh adam constant 750 0.0000000001

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fwe
Input X must be non-negative.

Error on calculation scores - fitting
Toxicophores # MinMaxScaler # SelectFdr 0.40 chi2 # ExtraTreesClassifier 75 gini 12 12 8 log2 None

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 363, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on feature selection - select_fdr
Input X must be non-negative.

Error on calculation scores - fitting
Fragments # MinMaxScaler # SelectFpr 0.50 f_classif # NeuroNets 25 1 tanh adam constant 750 0.0000000001

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Toxicophores # MinMaxScaler # SelectFdr 0.40 chi2 # ExtraTreesClassifier 75 gini 12 12 8 log2 None

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 363, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on calculation scores - fitting
Fragments # MinMaxScaler # SelectFpr 0.50 f_classif # NeuroNets 25 1 tanh adam constant 750 0.0000000001

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # RobustScaler True True # SelectFdr 0.25 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # RobustScaler True True # SelectFdr 0.25 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # RobustScaler True True # SelectFdr 0.25 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - select_fdr
Input X must be non-negative.

Error on feature selection - variance_threshold
ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>

Error on feature selection - select_fdr
Input X must be non-negative.

Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # StandardScaler False False # SelectFdr 0.25 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # StandardScaler False False # SelectFdr 0.25 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors Toxicophores Fragments # Normalizer max # SelectFwe 0.50 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # StandardScaler False False # SelectFdr 0.25 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors Toxicophores Fragments # Normalizer max # SelectFwe 0.50 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # RobustScaler True True # SelectFpr 0.55 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors Toxicophores Fragments # Normalizer max # SelectFwe 0.50 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # RobustScaler True True # SelectFpr 0.55 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # RobustScaler True True # SelectFpr 0.55 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # NoScaling # SelectFpr 0.55 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - select_fwe
Input X must be non-negative.

Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # NoScaling # SelectFpr 0.55 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # StandardScaler False False # SelectFdr 0.70 chi2 # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # NoScaling # SelectFpr 0.55 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # StandardScaler False False # SelectFdr 0.70 chi2 # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # StandardScaler False False # SelectFdr 0.70 chi2 # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - variance_threshold
ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>

Error on calculation scores - fitting
Toxicophores # NoScaling # SelectFdr 0.25 f_classif # GradientBoostingClassifier 2500 friedman_mse 7 9 6 sqrt exponential

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 659, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on calculation scores - fitting
Toxicophores # NoScaling # SelectFdr 0.25 f_classif # GradientBoostingClassifier 2500 friedman_mse 7 9 6 sqrt exponential

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 659, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on calculation scores - fitting
Toxicophores # NoScaling # SelectFdr 0.25 f_classif # GradientBoostingClassifier 2500 friedman_mse 7 9 6 sqrt exponential

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 659, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.70000

Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.60000

Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - select_fdr
Input X must be non-negative.

Error on calculation scores - fitting
Fragments # MinMaxScaler # SelectFpr 0.50 f_classif # NeuroNets 25 1 tanh adam constant 750 0.0000000001

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Fragments # MinMaxScaler # SelectFpr 0.50 f_classif # NeuroNets 25 1 tanh adam constant 750 0.0000000001

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_percentile
Input X must be non-negative.

Error on calculation scores - fitting
Fragments # MinMaxScaler # SelectFpr 0.50 f_classif # NeuroNets 25 1 tanh adam constant 750 0.0000000001

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # RobustScaler True True # SelectFdr 0.25 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Toxicophores # MinMaxScaler # SelectFdr 0.40 chi2 # ExtraTreesClassifier 75 gini 12 12 8 log2 None

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 363, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # RobustScaler True True # SelectFdr 0.25 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Toxicophores # MinMaxScaler # SelectFdr 0.40 chi2 # ExtraTreesClassifier 75 gini 12 12 8 log2 None

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 363, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # RobustScaler True True # SelectFdr 0.25 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Toxicophores # MinMaxScaler # SelectFdr 0.40 chi2 # ExtraTreesClassifier 75 gini 12 12 8 log2 None

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 363, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on feature selection - select_fdr
Input X must be non-negative.

Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - variance_threshold
ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>

Error on feature selection - select_fdr
Input X must be non-negative.

Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # StandardScaler False False # SelectFdr 0.25 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # StandardScaler False False # SelectFdr 0.25 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # StandardScaler False False # SelectFdr 0.25 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors Toxicophores Fragments # Normalizer max # SelectFwe 0.50 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # RobustScaler True True # SelectFpr 0.55 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors Toxicophores Fragments # Normalizer max # SelectFwe 0.50 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # RobustScaler True True # SelectFpr 0.55 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors Toxicophores Fragments # Normalizer max # SelectFwe 0.50 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # RobustScaler True True # SelectFpr 0.55 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # NoScaling # SelectFpr 0.55 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # NoScaling # SelectFpr 0.55 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fwe
Input X must be non-negative.

Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # NoScaling # SelectFpr 0.55 f_classif # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # StandardScaler False False # SelectFdr 0.70 chi2 # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # StandardScaler False False # SelectFdr 0.70 chi2 # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fwe
Input X must be non-negative.

Error on calculation scores - fitting
Graph_based_Signatures Toxicophores # StandardScaler False False # SelectFdr 0.70 chi2 # NeuroNets 50 5 identity adam adaptive 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - variance_threshold
ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>

Error on calculation scores - fitting
Toxicophores # NoScaling # SelectFdr 0.25 f_classif # GradientBoostingClassifier 2500 friedman_mse 7 9 6 sqrt exponential

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 659, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on calculation scores - fitting
Toxicophores # NoScaling # SelectFdr 0.25 f_classif # GradientBoostingClassifier 2500 friedman_mse 7 9 6 sqrt exponential

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 659, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on calculation scores - fitting
Toxicophores # NoScaling # SelectFdr 0.25 f_classif # GradientBoostingClassifier 2500 friedman_mse 7 9 6 sqrt exponential

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 659, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


