Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.60000

Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.80000

Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.80000

Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - variance_threshold
ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>

Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores # NoScaling # SelectPercentile 30 f_classif # NeuroNets 750 100 100 identity sgd invscaling 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.65000

Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores # NoScaling # SelectPercentile 30 f_classif # NeuroNets 750 100 100 identity sgd invscaling 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - select_percentile
Input X must be non-negative.

Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores # NoScaling # SelectPercentile 30 f_classif # NeuroNets 750 100 100 identity sgd invscaling 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - variance_threshold
when `importance_getter=='auto'`, the underlying estimator SVC should have `coef_` or `feature_importances_` attribute. Either pass a fitted estimator to feature selector or call fit before calling transform.

Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.65000

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.80000

Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - variance_threshold
ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>

Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.80000

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.60000

Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores # NoScaling # SelectPercentile 30 f_classif # NeuroNets 750 100 100 identity sgd invscaling 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores # NoScaling # SelectPercentile 30 f_classif # NeuroNets 750 100 100 identity sgd invscaling 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores # NoScaling # SelectPercentile 30 f_classif # NeuroNets 750 100 100 identity sgd invscaling 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - variance_threshold
when `importance_getter=='auto'`, the underlying estimator SVC should have `coef_` or `feature_importances_` attribute. Either pass a fitted estimator to feature selector or call fit before calling transform.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.65000

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.80000

Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.80000

Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - variance_threshold
ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>

Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.60000

Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores # NoScaling # SelectPercentile 30 f_classif # NeuroNets 750 100 100 identity sgd invscaling 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores # NoScaling # SelectPercentile 30 f_classif # NeuroNets 750 100 100 identity sgd invscaling 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores # NoScaling # SelectPercentile 30 f_classif # NeuroNets 750 100 100 identity sgd invscaling 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - variance_threshold
when `importance_getter=='auto'`, the underlying estimator SVC should have `coef_` or `feature_importances_` attribute. Either pass a fitted estimator to feature selector or call fit before calling transform.

Error on feature selection - select_fwe
Input X must be non-negative.

Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.65000

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.80000

Error on feature selection - variance_threshold
ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>

Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.60000

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.80000

Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores # NoScaling # SelectPercentile 30 f_classif # NeuroNets 750 100 100 identity sgd invscaling 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores # NoScaling # SelectPercentile 30 f_classif # NeuroNets 750 100 100 identity sgd invscaling 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on calculation scores - fitting
Advanced_Descriptors Graph_based_Signatures Toxicophores # NoScaling # SelectPercentile 30 f_classif # NeuroNets 750 100 100 identity sgd invscaling 1500 0.09

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 434, in _fit
    if np.any(np.array(hidden_layer_sizes) <= 0):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>


Error on feature selection - variance_threshold
when `importance_getter=='auto'`, the underlying estimator SVC should have `coef_` or `feature_importances_` attribute. Either pass a fitted estimator to feature selector or call fit before calling transform.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.35000

Error on feature selection - select_fdr
Input X must be non-negative.

Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.55000

Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors Graph_based_Signatures Toxicophores Fragments # NoScaling # SelectFpr 0.0 f_classif # SVM rbf 9 0.04 750 None

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/svm/_base.py", line 190, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors Graph_based_Signatures Toxicophores Fragments # NoScaling # SelectFpr 0.0 f_classif # SVM rbf 9 0.04 750 None

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/svm/_base.py", line 190, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on calculation scores - fitting
General_Descriptors Advanced_Descriptors Graph_based_Signatures Toxicophores Fragments # NoScaling # SelectFpr 0.0 f_classif # SVM rbf 9 0.04 750 None

All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/svm/_base.py", line 190, in fit
    X, y = self._validate_data(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/home/alexgcsa/anaconda3/envs/autoadmet/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required


Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - select_fdr
Input X must be non-negative.

Error on feature selection - variance_threshold
when `importance_getter=='auto'`, the underlying estimator MLPClassifier should have `coef_` or `feature_importances_` attribute. Either pass a fitted estimator to feature selector or call fit before calling transform.

Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - variance_threshold
ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>

Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.40000

Error on feature selection - select_fdr
Input X must be non-negative.

Error on feature selection - select_percentile
Input X must be non-negative.

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 0.85000

Error on feature selection - variance_threshold
No feature in X meets the variance threshold 1.00000

Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - select_fpr
Input X must be non-negative.

Error on feature selection - variance_threshold
when `importance_getter=='auto'`, the underlying estimator SVC should have `coef_` or `feature_importances_` attribute. Either pass a fitted estimator to feature selector or call fit before calling transform.

